victim_company = "MikeNet"
victim-network-vnet-cidr = "10.1.0.0/16"
victim-network-subnet-cidr = "10.1.0.0/24"
environment = "Staging"
vulnvm-name = "VulnServer"
username = "mike"
password = "Vpn123vpn123!"